/**
 * Build lib/client.js from src/client/ with esbuild.
 *
 * React is a platform seed module and MUST stay external — bundling a second
 * copy breaks hooks at runtime. Output mirrors what dsh-client-modules expects:
 * a single window.__ModuleLoader__.load({ id, factory }) handoff whose factory
 * returns the module exports (apply / inject).
 *
 * The module id is read from package.json rather than repeated here: the id IS
 * the package name, two copies of it drift, and the failure is silent — the host
 * serves the bundle under the manifest name while the banner registers another,
 * so the settings page never appears and nothing is logged.
 */
import { build } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const entry = resolve(root, 'src/client/index.js');
const outfile = resolve(root, 'lib/client.js');
const manifest = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
const id = manifest.name;
if (typeof id !== 'string' || id === '') {
  throw new Error('package.json has no "name" — the client bundle id has nothing to read');
}
const watch = process.argv.includes('--watch');

const banner =
  '// ' +
  id +
  ' client bundle — generated by scripts/build-client.mjs from src/client/, do not edit.\n' +
  'window.__ModuleLoader__.load({\n' +
  '\tid: ' +
  JSON.stringify(id) +
  ',\n' +
  '\tfactory: (require) => {\n' +
  '\t\tvar module = { exports: {} };\n' +
  '\t\tvar exports = module.exports;\n' +
  '\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });\n';
const footer = '\n\t\treturn module.exports;\n\t}\n});\n';

const options = {
  entryPoints: [entry],
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  external: ['react'],
  minify: false,
  target: ['es2020'],
  banner: { js: banner },
  footer: { js: footer },
  logLevel: 'info',
};

if (watch) {
  const context = await build({ ...options, write: false });
  const write = (result) => {
    const out = result.outputFiles[0];
    if (out) {
      writeFileSync(outfile, out.text);
      console.log('[dsh-paper-digest] wrote', outfile);
    }
  };
  write(await context.rebuild());
  await context.watch({
    onRebuild: (error, result) => {
      if (error) {
        console.error('[dsh-paper-digest] build failed:', error.message);
        return;
      }
      write(result);
    },
  });
  console.log('[dsh-paper-digest] watching src/client for changes…');
} else {
  const result = await build({ ...options, write: false });
  const out = result.outputFiles[0];
  if (!out) throw new Error('esbuild produced no JS output');
  writeFileSync(outfile, out.text);
  console.log('[dsh-paper-digest] wrote', outfile, '(' + out.text.length + ' bytes)');
}
